In [56]:
import numpy as np 
import pandas as pd
from sqlalchemy import create_engine

In [57]:
df_raw = pd.read_csv('../data/interim/master_table.csv')
df = df_raw.copy()

In [58]:
df.shape

(110197, 15)

In [59]:
df.head(10)

,order_id,product_id,seller_id,order_item_id,price,freight_value,customer_id,order_purchase_timestamp,order_status,product_category_name,product_category_name_english,customer_state,customer_city,seller_state,date
0,00010242fe8c5a6d1ba2dd792cb16214,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,1,58.90,13.29,3ce436f183e68e07877b285a838db11a,2017-09-13 08:59:02,delivered,cool_stuff,cool_stuff,RJ,campos dos goytacazes,SP,2017-09-13
1,00018f77f2f0320c557190d7a144bdd3,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,1,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,2017-04-26 10:53:06,delivered,pet_shop,pet_shop,SP,santa fe do sul,SP,2017-04-26
2,000229ec398224ef6ca0657da4fc703e,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,1,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,2018-01-14 14:33:31,delivered,moveis_decoracao,furniture_decor,MG,para de minas,MG,2018-01-14
3,00024acbcdf0a6daa1e931b038114c75,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,1,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,2018-08-08 10:00:35,delivered,perfumaria,perfumery,SP,atibaia,SP,2018-08-08
4,00042b26cf59d7ce69dfabb4e55b4fd9,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,1,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,2017-02-04 13:57:51,delivered,ferramentas_jardim,garden_tools,SP,varzea paulista,PR,2017-02-04
5,00048cc3ae777c65dbb7d2a0634bc1ea,ef92defde845ab8450f9d70c526ef70f,6426d21aca402a131fc0a5d0960a3c90,1,21.90,12.69,816cbea969fe5b689b39cfc97a506742,2017-05-15 21:42:34,delivered,utilidades_domesticas,housewares,MG,uberaba,SP,2017-05-15
6,00054e8431b9d7675808bcb819fb4a32,8d4f2bb7e93e6710a28f34fa83ee7d28,7040e82f899a04d1b434b795a43b4617,1,19.90,11.85,32e2e6ab09e778d99bf2e0ecd4898718,2017-12-10 11:53:48,delivered,telefonia,telephony,SP,guararapes,SP,2017-12-10
7,000576fe39319847cbb9d288c5617fa6,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,1,810.00,70.75,9ed5e522dd9dd85b4af4a077526d8117,2018-07-04 12:08:27,delivered,ferramentas_jardim,garden_tools,SP,praia grande,SP,2018-07-04
8,0005a1a1728c9d785b8e2b08b904576c,310ae3c140ff94b03219ad0adc3c778f,a416b6a846a11724393025641d4edd5e,1,145.95,11.65,16150771dfd4776261284213b89c304e,2018-03-19 18:40:33,delivered,beleza_saude,health_beauty,SP,santos,SP,2018-03-19
9,0005f50442cb953dcd1d21e1fb923495,4535b0e1091c278dfd193e5a1d63b39f,ba143b05f0110f0dc71ad71b4466ce92,1,53.99,11.40,351d3cb2cee3c7fd0af6616c82df21d3,2018-07-02 13:59:39,delivered,livros_tecnicos,books_technical,SP,jandira,SP,2018-07-02

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110197 entries, 0 to 110196
Data columns (total 15 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       110197 non-null  object
 1   product_id                     110197 non-null  object
 2   seller_id                      110197 non-null  object
 3   order_item_id                  110197 non-null  int64
 4   price                          110197 non-null  float64
 5   freight_value                  110197 non-null  float64
 6   customer_id                    110197 non-null  object
 7   order_purchase_timestamp       110197 non-null  object
 8   order_status                   110197 non-null  object
 9   product_category_name          108660 non-null  object
 10  product_category_name_english  108638 non-null  object
 11  customer_state                 110197 non-null  object
 12  customer_city                  110197 non-null  object
 13  seller_state                   110197 non-null  object
 14  date                           110197 non-null  object
dtypes: float64(2), int64(1), object(12)
memory usage: 12.6+ MB

In [61]:
df.isnull().sum()

order_id                            0
product_id                          0
seller_id                           0
order_item_id                       0
price                               0
freight_value                       0
customer_id                         0
order_purchase_timestamp            0
order_status                        0
product_category_name            1537
product_category_name_english    1559
customer_state                      0
customer_city                       0
seller_state                        0
date                                0
dtype: int64

In [62]:
df.duplicated().sum()

np.int64(0)

In [63]:
df['product_category_name_english'].nunique()

71

In [64]:
print(df['date'].min())
print(df['date'].max())

2016-09-15
2018-08-29

In [65]:
df[df['price'] <= 0]

Empty DataFrame
Columns: [order_id, product_id, seller_id, order_item_id, price, freight_value, customer_id, order_purchase_timestamp, order_status, product_category_name, product_category_name_english, customer_state, customer_city, seller_state, date]
Index: []

In [66]:
df['order_status'].value_counts()

order_status
delivered    110197
Name: count, dtype: int64

In [67]:
df[df['freight_value'] < 0]

Empty DataFrame
Columns: [order_id, product_id, seller_id, order_item_id, price, freight_value, customer_id, order_purchase_timestamp, order_status, product_category_name, product_category_name_english, customer_state, customer_city, seller_state, date]
Index: []

In [68]:
df['freight_value'].describe()

count    110197.000000
mean         19.948598
std          15.698136
min           0.000000
25%          13.080000
50%          16.260000
75%          21.150000
max         409.680000
Name: freight_value, dtype: float64

In [69]:
df = df.dropna(subset=['product_category_name_english'])

In [70]:
df['product_category_name_english'].value_counts()

product_category_name_english
bed_bath_table               10953
health_beauty                 9465
sports_leisure                8431
furniture_decor               8160
computers_accessories         7644
                             ...
arts_and_craftmanship           24
cds_dvds_musicals               14
la_cuisine                      14
fashion_childrens_clothes        7
security_and_services            2
Name: count, Length: 71, dtype: int64

In [71]:
cat_sales = (
    df.groupby('product_category_name_english')['order_item_id']
      .count()
      .sort_values(ascending=False)
)

cum_perc = (cat_sales.cumsum() / cat_sales.sum()) * 100

In [72]:
threshold = 80
head_value = (cum_perc <= threshold).sum() + 1
print(f"The number of categories making up more than 80% is: {head_value}")
print(cum_perc.head(head_value))

The number of categories making up more than 80% is: 15
product_category_name_english
bed_bath_table           10.082108
health_beauty            18.794529
sports_leisure           26.555165
furniture_decor          34.066349
computers_accessories    41.102561
housewares               47.357278
watches_gifts            52.750419
telephony                56.828182
garden_tools             60.756825
auto                     64.567647
toys                     68.277214
cool_stuff               71.699589
perfumery                74.774020
baby                     77.518916
electronics              80.030928
Name: order_item_id, dtype: float64

In [73]:
state_sales = (
    df.groupby('customer_state')['order_item_id']
      .count()
      .sort_values(ascending=False)
)

cum_st_perc = (state_sales.cumsum() / state_sales.sum()) * 100

In [74]:
head_value_st = (cum_st_perc <= threshold).sum() + 1
print(f"The number of states making up more than 80% is: {head_value_st}")
cum_st_perc.head(head_value_st)

The number of states making up more than 80% is: 6

customer_state
SP    42.170327
RJ    54.990887
MG    66.712384
RS    72.270292
PR    77.399253
SC    81.115264
Name: order_item_id, dtype: float64

In [75]:
df['order_purchase_timestamp'].sort_values().head()

82574    2016-09-15 12:16:38
82573    2016-09-15 12:16:38
82572    2016-09-15 12:16:38
25526    2016-10-03 09:44:50
82005    2016-10-03 16:56:50
Name: order_purchase_timestamp, dtype: object

In [76]:
df['order_purchase_timestamp'].sort_values().tail()

4827     2018-08-29 14:18:23
4828     2018-08-29 14:18:23
9617     2018-08-29 14:18:28
1691     2018-08-29 14:52:00
23001    2018-08-29 15:00:37
Name: order_purchase_timestamp, dtype: object

In [77]:
df.groupby('order_id')['order_item_id'].count().describe()

count    95127.000000
mean         1.142031
std          0.538648
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         21.000000
Name: order_item_id, dtype: float64

In [78]:
top_categories = (
    df.groupby('product_category_name_english')['order_item_id']
    .count()
    .sort_values(ascending=False)
    .head(head_value)
)
top_categories

product_category_name_english
bed_bath_table           10953
health_beauty             9465
sports_leisure            8431
furniture_decor           8160
computers_accessories     7644
housewares                6795
watches_gifts             5859
telephony                 4430
garden_tools              4268
auto                      4140
toys                      4030
cool_stuff                3718
perfumery                 3340
baby                      2982
electronics               2729
Name: order_item_id, dtype: int64

In [79]:
top_states = (
    df.groupby('customer_state')['order_item_id']
    .count()
    .sort_values(ascending=False)
    .head(head_value_st)
)
top_categories

product_category_name_english
bed_bath_table           10953
health_beauty             9465
sports_leisure            8431
furniture_decor           8160
computers_accessories     7644
housewares                6795
watches_gifts             5859
telephony                 4430
garden_tools              4268
auto                      4140
toys                      4030
cool_stuff                3718
perfumery                 3340
baby                      2982
electronics               2729
Name: order_item_id, dtype: int64

In [80]:
top_categories = top_categories.index.tolist()
top_categories

['bed_bath_table',
 'health_beauty',
 'sports_leisure',
 'furniture_decor',
 'computers_accessories',
 'housewares',
 'watches_gifts',
 'telephony',
 'garden_tools',
 'auto',
 'toys',
 'cool_stuff',
 'perfumery',
 'baby',
 'electronics']

In [81]:
top_states = top_states.index.tolist()
top_states

['SP', 'RJ', 'MG', 'RS', 'PR', 'SC']

In [82]:
df['product_category_name_english'] = df['product_category_name_english'].apply(
    lambda x: x if x in top_categories else 'Other'
)

In [83]:
df['customer_state'] = df['customer_state'].apply(
    lambda x: x if x in top_states else 'Other'
)

In [84]:
daily_sales = df.groupby(
    ['date','product_category_name_english','customer_state']
).agg(
    sales=('order_item_id','count'),
    revenue=('price','sum')
).reset_index()

In [85]:
daily_sales = daily_sales.rename(columns={
    "product_category_name_english": "category",
    "customer_state": "state"
})

In [86]:
daily_sales = daily_sales.sort_values(
    ['date','state','category']
).reset_index(drop=True)

In [87]:
daily_sales.head(10)

         date         category  state  sales  revenue
0  2016-09-15    health_beauty     SP      3   134.97
1  2016-10-03  furniture_decor     MG      1    74.90
2  2016-10-03             toys  Other      1   128.90
3  2016-10-03   sports_leisure     RS      2    58.39
4  2016-10-03            Other     SP      1    29.99
5  2016-10-03  furniture_decor     SP      1   119.90
6  2016-10-03    watches_gifts     SP      1    29.90
7  2016-10-04            Other     MG      1   299.99
8  2016-10-04             baby     MG      1   199.99
9  2016-10-04  furniture_decor     MG      1    19.90

In [88]:
daily_sales['state'].value_counts()

state
SP       8332
Other    6797
RJ       5741
MG       5486
RS       3616
PR       3334
SC       2632
Name: count, dtype: int64

In [89]:
daily_sales['category'].value_counts()

category
Other                    3579
bed_bath_table           2808
health_beauty            2692
sports_leisure           2675
furniture_decor          2603
computers_accessories    2465
housewares               2368
watches_gifts            2172
telephony                2033
cool_stuff               2007
toys                     1943
garden_tools             1898
auto                     1858
perfumery                1713
baby                     1661
electronics              1463
Name: count, dtype: int64

In [90]:
daily_sales['date'] = pd.to_datetime(daily_sales['date'])

In [91]:
daily_sales.groupby(['category','state']).ngroups

112

In [92]:
daily_sales['date'].is_monotonic_increasing

True

In [93]:
daily_sales.groupby(['category','state'])['date'].count().describe()

count    112.000000
mean     320.875000
std      143.184636
min       90.000000
25%      197.750000
50%      298.000000
75%      436.750000
max      600.000000
Name: date, dtype: float64

In [94]:
full_date_range = pd.date_range(
    start=daily_sales['date'].min(),
    end=daily_sales['date'].max()
)
print(full_date_range)

DatetimeIndex(['2016-09-15', '2016-09-16', '2016-09-17', '2016-09-18',
               '2016-09-19', '2016-09-20', '2016-09-21', '2016-09-22',
               '2016-09-23', '2016-09-24',
               ...
               '2018-08-20', '2018-08-21', '2018-08-22', '2018-08-23',
               '2018-08-24', '2018-08-25', '2018-08-26', '2018-08-27',
               '2018-08-28', '2018-08-29'],
              dtype='datetime64[ns]', length=714, freq='D')

In [95]:
filled_list = []

for (category, state), group in daily_sales.groupby(['category','state']):
    
    group = group.copy()
    group['date'] = pd.to_datetime(group['date'])   # 🔥 ensure match
    group = group.set_index('date')
    
    group = group.reindex(full_date_range)
    
    group['category'] = category
    group['state'] = state
    group['sales'] = group['sales'].fillna(0)
    group['revenue'] = group['revenue'].fillna(0)
    
    group = group.reset_index().rename(columns={'index': 'date'})
    
    filled_list.append(group)

daily_sales_filled = pd.concat(filled_list, ignore_index=True)

In [96]:
daily_sales_filled = daily_sales_filled.sort_values(
    ['category','state','date']
).reset_index(drop=True)

In [97]:
daily_sales_filled.groupby(['category','state'])['date'].count().describe()

count    112.0
mean     714.0
std        0.0
min      714.0
25%      714.0
50%      714.0
75%      714.0
max      714.0
Name: date, dtype: float64

In [98]:
daily_sales_filled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79968 entries, 0 to 79967
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      79968 non-null  datetime64[ns]
 1   category  79968 non-null  object
 2   state     79968 non-null  object
 3   sales     79968 non-null  float64
 4   revenue   79968 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 3.1+ MB

In [99]:
(daily_sales_filled['sales'] == 0).mean() * 100

np.float64(55.05952380952381)

In [100]:
count = (daily_sales_filled['sales']==0).sum()
print(count)

44030

In [101]:
percentage = (daily_sales_filled["sales"] == 0).mean() * 100
print(f"{percentage}%")

55.05952380952381%

In [102]:
daily_sales_filled['date'] = pd.to_datetime(daily_sales_filled['date'])

df_weekly = daily_sales_filled.copy()
df_weekly = df_weekly.set_index('date')

In [103]:
daily_sales_filled['date'] = pd.to_datetime(daily_sales_filled['date'])

df_weekly = daily_sales_filled.copy()
df_weekly = df_weekly.set_index('date')

In [104]:
df_weekly = df_weekly.groupby(['category','state']).resample('W').agg({
    'sales': 'sum',
    'revenue': 'sum'
}).reset_index()

In [105]:
df_weekly.head()

  category state       date  sales  revenue
0    Other    MG 2016-09-18    0.0     0.00
1    Other    MG 2016-09-25    0.0     0.00
2    Other    MG 2016-10-02    0.0     0.00
3    Other    MG 2016-10-09    5.0   622.76
4    Other    MG 2016-10-16    0.0     0.00

In [106]:
df_weekly.shape

(11536, 5)

In [107]:
(df_weekly['sales'] == 0).mean() * 100

np.float64(22.824202496532596)

In [108]:
df_weekly.groupby(['category','state'])['date'].count().describe()

count    112.0
mean     103.0
std        0.0
min      103.0
25%      103.0
50%      103.0
75%      103.0
max      103.0
Name: date, dtype: float64

In [109]:
percentage = (df_weekly["sales"] == 0).mean() * 100
print(f"{percentage}%")

22.824202496532596%

In [110]:
df_weekly.to_csv('../data/interim/Data_cleaned_weekly.csv',index=False)