In [1]:
import numpy as np
import pandas as pd
from sqlalchemy import create_engine

In [2]:
engine = create_engine('postgresql://postgres:soham%4027@localhost:5432/Olist_Ecommerce')

In [3]:
df_true = pd.read_csv('../data/interim/Data_cleaned_weekly.csv')
df = df_true.copy()

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11536 entries, 0 to 11535
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   category  11536 non-null  object
 1   state     11536 non-null  object
 2   date      11536 non-null  object
 3   sales     11536 non-null  float64
 4   revenue   11536 non-null  float64
dtypes: float64(2), object(3)
memory usage: 450.8+ KB

In [5]:
df.shape

(11536, 5)

In [6]:
df['date'] = pd.to_datetime(df['date'])

In [7]:
df.head(10)

  category state       date  sales  revenue
0    Other    MG 2016-09-18    0.0     0.00
1    Other    MG 2016-09-25    0.0     0.00
2    Other    MG 2016-10-02    0.0     0.00
3    Other    MG 2016-10-09    5.0   622.76
4    Other    MG 2016-10-16    0.0     0.00
5    Other    MG 2016-10-23    0.0     0.00
6    Other    MG 2016-10-30    0.0     0.00
7    Other    MG 2016-11-06    0.0     0.00
8    Other    MG 2016-11-13    0.0     0.00
9    Other    MG 2016-11-20    0.0     0.00

In [8]:
count = (df["sales"] == 0).sum()
print(count)

2633

In [9]:
df = df.sort_values(['category', 'state', 'date']).reset_index(drop=True)

In [10]:
df['month'] = df['date'].dt.month
df['week_of_year'] = df['date'].dt.isocalendar().week.astype(int)

In [11]:
df['lag_1'] = df.groupby(['category', 'state'])['sales'].shift(1)
df['lag_2'] = df.groupby(['category', 'state'])['sales'].shift(2)
df['lag_4'] = df.groupby(['category', 'state'])['sales'].shift(4)
df['lag_8'] = df.groupby(['category', 'state'])['sales'].shift(8)

In [12]:
df['revenue_lag_1'] = df.groupby(['category', 'state'])['revenue'].shift(1)

In [13]:
df['rolling_mean_4'] = df.groupby(['category', 'state'])['sales'] \
                        .shift(1).rolling(4).mean()

df['rolling_std_4'] = df.groupby(['category', 'state'])['sales'] \
                       .shift(1).rolling(4).std()

In [14]:
df['is_black_friday_week'] = (
    (df['date'].dt.month == 11) &
    (df['week_of_year'].between(47, 48))
).astype(int)

df['is_christmas_week'] = (
    (df['date'].dt.month == 12) &
    (df['date'].dt.day >= 20)
).astype(int)

In [15]:
df = df.dropna(subset=[
    'lag_1', 'lag_2', 'lag_4','lag_8',
    'rolling_mean_4', 'rolling_std_4'
])

In [16]:
print("Final Shape:", df.shape)
print("Zero Sales %:", (df['sales'] == 0).mean() * 100)

Final Shape: (10640, 16)
Zero Sales %: 17.236842105263158

In [17]:
df.head()

,category,state,date,sales,revenue,month,week_of_year,lag_1,lag_2,lag_4,lag_8,revenue_lag_1,rolling_mean_4,rolling_std_4,is_black_friday_week,is_christmas_week
8,Other,MG,2016-11-13,0.0,0.0,11,45,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
9,Other,MG,2016-11-20,0.0,0.0,11,46,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0
10,Other,MG,2016-11-27,0.0,0.0,11,47,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0
11,Other,MG,2016-12-04,0.0,0.0,12,48,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0,0
12,Other,MG,2016-12-11,0.0,0.0,12,49,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0

In [18]:
df.to_csv('../data/processed/data_engineered_weekly.csv',index=False)